---
title: "HACKODS"
author: "Los cuadernos"
date: last-modified
lang: es
format: 
  dashboard:
    fontsize: 20pt
    theme:
      light: "solar"
      dark: "darkly"
    embed-resources: false
    code-fold: true
    toc: true
execute:
  echo: false   
  warning: false
  message: false
---

# La escasez de agua en México {scrolling="true"}

El agua es un recurso esencial para la vida, pero su disponibilidad y calidad están siendo amenazadas por diversos factores, como el cambio climático, la contaminación y el crecimiento demográfico.

# Prueba

Hola esto es una prueba
## Pito

### Análisis de Vulnerabilidad
{{< embed notebook/003_Analisis_vulnerabilidad.ipynb#pruebaA >}}

### Acuíferos críticos
{{< embed notebook/003_Analisis_vulnerabilidad.ipynb#AcuiferosCriticos >}}

### Priorización de intervencion
{{< embed notebook/003_Analisis_vulnerabilidad.ipynb#PriorizacionIntervencion >}}

### Relacion Disponibilidad e Infraestructura
{{< embed notebook/003_Analisis_vulnerabilidad.ipynb#relacion >}}

### Acuiferos con dispionibilidad pero baja infraestructura
{{< embed notebook/003_Analisis_vulnerabilidad.ipynb#AcuiferosDisponibilidadBajaInfraestructura >}}

### Mapeo de resitrcciones legales en zonas criticas
{{< embed notebook/003_Analisis_vulnerabilidad.ipynb#MapeoRestriccionesLegales >}}

# Mapas {scrolling="true"}

### MAPA 1: DISPONIBILIDAD DE AGUA SUBTERRÁNEA {width="100%" height="600px" style="border:none;"}
{{< embed notebook/004_Atlas_cartografico.ipynb#Mapa1 >}}

### MAPA 2: BRECHA DE INFRAESTRUCTURA
{{< embed notebook/004_Atlas_cartografico.ipynb#Mapa2 >}}

### MAPA 3: RESTRICCIONES LEGALES DE EXTRACCIÓN
{{< embed notebook/004_Atlas_cartografico.ipynb#Mapa3 >}}

# JAVI {scrolling="true"}
### Análisis de los datos de suministro diario de agua por entidad federativa
{{< embed notebook/All_Javivi.ipynb#analisisdatosporentidadfederativajavi >}}

### Evolución del suministro diario de agua por entidad federativa
{{< embed notebook/All_Javivi.ipynb#evolucionsuministroaguaporentidadfederativajavi >}}

### Mapa de Calor del suministro diario de agua (2008 -2022)
{{< embed notebook/All_Javivi.ipynb#mapacalorsuministrodiarioagua20082022javi >}}

### Visualizacion y analisis de los datos del porcetanje del servicio de agua entubada por entidad federativa
{{< embed notebook/All_Javivi.ipynb#visualizacionyanalisisdatosservicioaguaentubadaentidadfederativajavi >}}

### Evolucion del servicio de agua entubada por entidad federativa
{{< embed notebook/All_Javivi.ipynb#evolucionservicioaguaentubadaentidadfederativajavi >}}

### Mapa de Calor del servicio de agua entubada (1990 -2020)
{{< embed notebook/All_Javivi.ipynb#mapacalorservicioaguaentubada19902020javi >}}

### Visualizacion y analisis de los datos del porcetanje del indice de rezago social por entidad federativa
{{< embed notebook/All_Javivi.ipynb#visualizacionyanalisisdatosindice_rezago_socialentidadfederativajavi >}}

### Evolucion del indice de rezago social por entidad federativa
{{< embed notebook/All_Javivi.ipynb#evolucionindice_rezago_socialentidadfederativajavi >}}

### Mapa de Calor del indice de rezago social (2000 -2020)
{{< embed notebook/All_Javivi.ipynb#mapacalorindice_rezago_social20002020javi >}}



# Gráficas {scrolling="true"}

### Servicio de Agua Entubada
<iframe src="notebook/grafica_servicio_agua_entubada.html" width="100%" height="600px" style="border:none;"></iframe>

### Suministro de Agua
<iframe src="notebook/grafica_suministro_agua.html" width="100%" height="600px" style="border:none;"></iframe>

### Índice de Rezago Social
<iframe src="notebook/indice_de_rezago_social.html" width="100%" height="600px" style="border:none;"></iframe>

### Mapa de Calor: Rezago Social
<iframe src="notebook/mapa_calor_rezago_social.html" width="100%" height="600px" style="border:none;"></iframe>

### Mapa de Calor: Servicio de Agua
<iframe src="notebook/mapa_calor_servicio_agua_entubada.html" width="100%" height="600px" style="border:none;"></iframe>

### Mapa de Calor: Suministro Diario
<iframe src="notebook/mapa_calor_suministro_diario_agua.html" width="100%" height="600px" style="border:none;"></iframe>

# Soluciones {scrolling="true"}

### Impacto de estrategia hidrica 
{{< embed notebook/005_simulacion_solucion.ipynb#Estrategia >}}

### Transición de Infraestructura Hídrica: Impacto 2024-2030
{{< embed notebook/005_simulacion_solucion.ipynb#MapaAnimado >}}


### Union de los datos de disponibilidad de agua y la infraestructura hídrica para identificar zonas prioritarias de intervención
{{< embed notebook/All_Javivi.ipynb#UnionDatosjavi >}}


### Suministro de agua vs Reazgo social
{{< embed notebook/All_Javivi.ipynb#SuministroAguaVsRezagoSocialjavi >}}

### Relacion entre el suministro de agua y el índice de rezago social
{{< embed notebook/All_Javivi.ipynb#RelacionSuministroAguaIndiceRezagoSocialjavi >}}
{{< embed notebook/All_Javivi.ipynb#RelacionSuministroAguaIndiceRezagoSocialjavi1 >}}
{{< embed notebook/All_Javivi.ipynb#RelacionSuministroAguaIndiceRezagoSocialjavi2 >}}

### Suministro de agua vs Reazgo social: Análisis por entidad federativa
{{< embed notebook/All_Javivi.ipynb#SuministroAguaVsRezago >}}

### relacion entre el suministro de agua y el índice de rezago social por entidad federativa
{{< embed notebook/All_Javivi.ipynb#RelacionSuministroAguaIndiceRezagoSocialEntidadFederativajavi >}}
